<a href="https://colab.research.google.com/github/richardzhu64/mit-6036/blob/master/RZ_MIT_6_036_HW06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2020: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.

In [0]:
import numpy as np

# **Problem 2**

You may find it helpful to implement a softmax function to use for solving the problems.

In [0]:
# Implement Softmax
def SM(z):
    e_z = np.exp(z)
    total = np.sum(e_z)
    return e_z / total


**Problem 2.A**

In [0]:
z = np.array([[-1, 0, 1]]).T
print(SM(z))

[[0.09003057]
 [0.24472847]
 [0.66524096]]


**Problem 2.C - 2.F**

In [0]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

z = w.T@x
grad_w = ((SM(z)-y)@x.T).T

w_step_one = w - .5 * grad_w
print(w_step_one)
print(SM(w_step_one.T@x))

[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
[[0.15918761]
 [0.77245284]
 [0.06835955]]


# **Problem 3**

**Problem 3.1**

You may choose to draft your implementation here. We recommend looking at the ReLU plot at the top of the homework page for better understanding.

In [0]:
def cv(value_list):
    return np.array([value_list]).T

def ReLU(z):
  return np.where(z > 0, z, 0)

def dReLU_dz(z):
    return np.where(z > 0, 1, 0)

x = cv([3,14])
w_1 = np.array([[1, 0 , -1, 0], [0, 1, 0 ,-1]])
w_1_0 = cv([-1,-1,-1,-1])
w_2 = np.array([[1,-1],[1,-1],[1,-1],[1,-1]])
w_2_0 = cv([0, 2])

# hidden layer
a_1 = ReLU(w_1.T@x + w_1_0)
a_2 = SM(w_2.T@a_1 + w_2_0)
print(a_2)

[[1.00000000e+00]
 [6.91440011e-13]]
